# Generated by Django 5.1.7 on 2025-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_profile_delete_mynewtable_recipe_createdon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='description',
            field=models.TextField(default='This is a generic description.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to='static/images'),
        ),
    ]
