# Generated by Django 5.1.7 on 2025-03-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_recipe_recipe_image_alter_recipeimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
    ]
